server:
  port: 45671
  servlet:
    context-path: /management
logging:
  config: classpath:log4j-dev.xml
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/anov-admin?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为，默认值：true
      pool-name: HikariConnectionPool
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟)
      max-lifetime: 1800000 #控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 10000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-wait: 3000ms
        min-idle: 0
        max-idle: 10
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
sa-token:
  token-name: X-ANOV-ACCESS-TOKEN # token名称 (同时也是cookie名称)
  timeout: 2592000 # token有效期，单位s 默认30天, -1代表永不过期
  activity-timeout: -1 # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  is-concurrent: true # 是否允许同一账号并发登录(为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-share: true # 在多人登录同一账号时(为true共用一个token, 为false每次登录新建一个token)
  token-style: uuid # token风格
  is-log: false # 是否输出操作日志
anov:
  mgt:
    tenant:
      ignores-tables:
        - sys_role
        - sys_role_user_relation
        - sys_role_func_relation
        - sys_func
        - sys_tenant