server:
  port: 45671
  servlet:
    context-path: /management
# 如果使用https，请放开下面的注释
#  ssl:
#    enabled: true
#    key-store: classpath:bms.keystore
#    key-store-type: PKCS12
#    key-alias: bms
#    key-password: 123456
#    key-store-password: 123456
logging:
  config: classpath:log4j-dev.xml
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/anov-admin?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为，默认值：true
      pool-name: HikariConnectionPool
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟)
      max-lifetime: 1800000 #控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 10000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-wait: 3000ms
        min-idle: 0
        max-idle: 10
    timeout: 5000
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  mail:
    host: smtp.qq.com
    username: 100103081@qq.com
    password: ltsjolgvxshibiii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
anov:
  security:
    signin: /signin
    signout: /signout
    ignore-urls:
      - /v1/tenants/**
      - /v1/verify-code/**
      - /v1/logger/v1/open
      - /v1/logger/v1/close
      - /swagger/**
      - /swagger-ui.html
      - /webjars/**
      - /v2/**
      - /v2/api-docs-ext/**
      - /swagger-resources/**
      - /doc.html
  mgt:
    tenant:
      ignores-tables:
        - sys_role
        - sys_role_user_relation
        - sys_role_func_relation
        - sys_func
        - sys_tenant
        - dev_screen_client
        - dev_screen_log
        - dev_screen_pic